# Generated by Django 6.0 on 2025-12-19 11:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='notes',
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='future_growth',
            field=models.FloatField(help_text='Growth percentage'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='careerpathskill',
            name='proficiency_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('course', 'Course'), ('book', 'Book'), ('tutorial', 'Tutorial'), ('article', 'Article'), ('video', 'Video'), ('documentation', 'Documentation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='match_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('ai_ml', 'AI / Machine Learning'), ('data_science', 'Data Science'), ('web_dev', 'Web Development'), ('cloud_devops', 'Cloud & DevOps'), ('databases', 'Databases'), ('tools', 'Tools'), ('soft_skills', 'Soft Skills')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
